##   --- --- --- --- --- --- --- --- --- --- 
## DO NOT EDIT THIS FILE                     
## MODIFY THE VERSION IN Path_dependent_files
if(sys.nframe() == 0) file.edit("Path_dependent_files/./Lib/common/03_export_project_helpers.R")
##   --- --- --- --- --- --- --- --- --- --- 

export_project_to_txt <- function() {
  sh(paste0("sh /sasdata/prd/users/42a001092210899/sasuser/RStudio_projects/_SNDS_TOOLS/Lib/shell_helpers/export-project-to-txt.sh"))
}

import_project_from_txt <- function(fichier) {
  sh(paste0("sh /sasdata/prd/users/42a001092210899/sasuser/RStudio_projects/_SNDS_TOOLS/Lib/shell_helpers/import-project-from-txt.sh ", fichier))  
}
