##   --- --- --- --- --- --- --- --- --- --- 
## DO NOT EDIT THIS FILE                     
## MODIFY THE VERSION IN Path_dependent_files
if(sys.nframe() == 0) file.edit("Path_dependent_files/./Lib/project_specific/04_update_tools.R")
##   --- --- --- --- --- --- --- --- --- --- 

update_tools <- function() {
  export_project_to_txt()
  current_project_path <- getwd()
  project_name <- str_extract(current_project_path, "[^/]*$")
  sh("mv ./R/01-sql-orchestration.R ./R/01-sql-orchestration.bak")
  sh("mv ./sql/00_user_macros.m4 ./sql/00_user_macros.m4.bak")
  setwd("/sasdata/prd/users/42a001092210899/sasuser/RStudio_projects/_SNDS_TOOLS")
  source("00-start-snds-tools.R")
  create_project(project_name, update = TRUE)
  setwd(current_project_path)
  sh("mv ./R/01-sql-orchestration.bak ./R/01-sql-orchestration.R ")
  sh("mv ./sql/00_user_macros.m4.bak ./sql/00_user_macros.m4")
  rm(list = ls(envir = .GlobalEnv), envir = .GlobalEnv)
  source("R/00-setup-new-session.R")
}