##   --- --- --- --- --- --- --- --- --- --- 
## DO NOT EDIT THIS FILE                     
## MODIFY THE VERSION IN Path_dependent_files
if(sys.nframe() == 0) file.edit("Path_dependent_files/./Skeleton_dir/R/00-setup-new-session.R")
##   --- --- --- --- --- --- --- --- --- --- 

## Synchronisation fuseaux (sinon décalage horaire)
Sys.setenv(TZ='UTC')
Sys.setenv(ORA_SDTZ='UTC')

source("/sasdata/prd/users/42a001092210899/sasuser/RStudio_projects/_SNDS_TOOLS/Lib/00-source-all-scripts-in-dir.R")
source_all_scripts_in_dir("/sasdata/prd/users/42a001092210899/sasuser/RStudio_projects/_SNDS_TOOLS/Lib/common/")
source_all_scripts_in_dir("/sasdata/prd/users/42a001092210899/sasuser/RStudio_projects/_SNDS_TOOLS/Lib/project_specific/")
