sed -i 's:<hard-coded-path>:'"$PWD"':g' $1

FINAL_DESTINATION_PATH=Path_dependent_files/`echo $1 | sed 's:/Tmp_path_dep_files::'`

echo    "##   --- --- --- --- --- --- --- --- --- --- "  >  tmpfile.032rfnds29e4
echo    "## DO NOT EDIT THIS FILE                     " >>  tmpfile.032rfnds29e4
echo    "## MODIFY THE VERSION IN Path_dependent_files" >>  tmpfile.032rfnds29e4
echo    "if(sys.nframe() == 0) file.edit(\"$FINAL_DESTINATION_PATH\")" >> tmpfile.032rfnds29e4
echo -e "##   --- --- --- --- --- --- --- --- --- --- \n" >> tmpfile.032rfnds29e4

cat $1 >> tmpfile.032rfnds29e4
mv tmpfile.032rfnds29e4 $1